#!/usr/bin/env bash
set -e
dir=$(dirname $(realpath ${BASH_SOURCE[0]}))
if [ ! -f $dir/patchelf ]; then
    if [ ! -d $dir/patchelf.git ]; then
        git clone https://github.com/nixos/patchelf $dir/patchelf.git
    fi
    cd $dir/patchelf.git
    ./bootstrap.sh
    ./configure
    make
    mv src/patchelf $dir/patchelf
    rm -rf $dir/patchelf.git
fi
