#!/usr/bin/env bash
set -e
interp=$(./patchelf --print-interpreter $1 || echo "")
echo "interpreter: \"$interp\""
rpath=$(./patchelf --print-rpath $1)
echo "rpath: \"$rpath\""
echo "----------------------------------"
readelf -d $1 | grep "library"
