#!/usr/bin/env python3
#
# Test a variety of packages that don't take that long to build
#
# NOTE: genesis will need to build tar-bootstrap/patch-bootstrap
#       which take a bit of time to build but they are needed to
#       build other packages.
#
import os
import sys

script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(script_dir, "py"))

import log
import genesis
import proc

#log.verbose_enabled = True

gen = os.path.join(script_dir, "gen")

if os.name == "nt":
    proc.py([gen, "add-build", "dmc-8.57-win-prebuilt"])
    proc.py([gen, "add-build", "dmd-2.085.1-win-prebuilt"])
    proc.py([gen, "make-env", "dmd-2.085.1-win-prebuilt"])
else:
    proc.py([gen, "add-build", "linux-glibc-dev-linux64"])
    #proc.py([gen, "add-build", "gnumake-linux64-prebuilt"])
    proc.py([gen, "add-build", "gnumake"])
    proc.py([gen, "add-build", "libattr1-2.4.47-linux64-prebuilt"])
    proc.py([gen, "add-build", "coreutils-8.28-linux64-prebuilt"])
    proc.py([gen, "make-env", "coreutils-8.28-linux64-prebuilt", "gnumake-linux64-prebuilt"])
